import '../models/response_block.dart';
import '../models/response_document.dart';
import '../models/response_section.dart';
import '../models/response_theme.dart';

class ResponseGeneratorService {
  ResponseGeneratorService();

  ResponseDocument generateDocument({
    String title = 'JourneyMATE AI Brain',
    String summary = '',
    String recommendationSummary = '',
    String travelPlanSummary = '',
    String reasoningSummary = '',
    String explanationSummary = '',
    double confidence = 0,
    ResponseTheme? theme,
    DateTime? generatedAt,
    Map<String, dynamic>? metadata,
  }) {
    try {
      final resolvedTheme = theme ?? ResponseTheme();
      final resolvedMetadata = <String, dynamic>{
        ..._normalizeMap(metadata),
        'confidence': _safeConfidence(confidence),
        'theme': resolvedTheme.toMap(),
        'formats': const <String>[
          'markdown',
          'plainText',
          'richCards',
          'json',
          'voiceSummary',
        ],
      };

      final sections = <ResponseSection>[
        generateRecommendationSection(recommendationSummary),
        generatePlannerSection(travelPlanSummary),
        generateReasoningSection(reasoningSummary),
        generateExplanationSection(explanationSummary),
      ];

      return ResponseDocument(
        title: _safeText(title, fallback: 'JourneyMATE AI Brain'),
        summary: generateTravelSummary(
          summary: summary,
          recommendationSummary: recommendationSummary,
          travelPlanSummary: travelPlanSummary,
          confidence: confidence,
        ),
        sections: sections,
        footer: buildFooter(confidence: confidence),
        generatedAt: generatedAt,
        metadata: resolvedMetadata,
      );
    } catch (error) {
      return _fallbackDocument(error);
    }
  }

  String generateTravelSummary({
    String summary = '',
    String recommendationSummary = '',
    String travelPlanSummary = '',
    double confidence = 0,
  }) {
    try {
      final explicitSummary = summary.trim();
      if (explicitSummary.isNotEmpty) {
        return explicitSummary;
      }

      final recommendation = recommendationSummary.trim();
      final plan = travelPlanSummary.trim();
      if (recommendation.isNotEmpty && plan.isNotEmpty) {
        return '$recommendation $plan';
      }
      if (recommendation.isNotEmpty) {
        return recommendation;
      }
      if (plan.isNotEmpty) {
        return plan;
      }

      final confidencePercent = (_safeConfidence(confidence) * 100)
          .toStringAsFixed(0);
      return 'JourneyMATE generated a structured travel response with '
          '$confidencePercent% confidence.';
    } catch (_) {
      return 'JourneyMATE generated a structured travel response.';
    }
  }

  ResponseSection generateRecommendationSection(String content) {
    return _buildSingleBlockSection(
      title: 'Recommendation Summary',
      subtitle: 'Best-fit travel guidance from the intelligence layer.',
      blockId: 'recommendation-summary',
      blockType: 'recommendation',
      blockTitle: 'Recommendation',
      content: content,
      icon: 'sparkles',
      priority: 10,
    );
  }

  ResponseSection generatePlannerSection(String content) {
    return _buildSingleBlockSection(
      title: 'Travel Plan Summary',
      subtitle: 'High-level plan structure for the journey.',
      blockId: 'travel-plan-summary',
      blockType: 'planner',
      blockTitle: 'Travel Plan',
      content: content,
      icon: 'map',
      priority: 20,
    );
  }

  ResponseSection generateReasoningSection(String content) {
    return _buildSingleBlockSection(
      title: 'Reasoning Summary',
      subtitle: 'Decision context behind the generated response.',
      blockId: 'reasoning-summary',
      blockType: 'reasoning',
      blockTitle: 'Reasoning',
      content: content,
      icon: 'brain',
      priority: 30,
    );
  }

  ResponseSection generateExplanationSection(String content) {
    return _buildSingleBlockSection(
      title: 'Explanation Summary',
      subtitle: 'User-facing explanation of why this response fits.',
      blockId: 'explanation-summary',
      blockType: 'explanation',
      blockTitle: 'Explanation',
      content: content,
      icon: 'info',
      priority: 40,
    );
  }

  String buildFooter({double confidence = 0}) {
    try {
      final confidencePercent = (_safeConfidence(confidence) * 100)
          .toStringAsFixed(0);
      return 'Generated by JourneyMATE Intelligent Response Generator. '
          'Confidence: $confidencePercent%.';
    } catch (_) {
      return 'Generated by JourneyMATE Intelligent Response Generator.';
    }
  }

  String exportMarkdown(ResponseDocument document) {
    try {
      final buffer = StringBuffer()
        ..writeln('# ${_safeText(document.title)}')
        ..writeln();

      if (document.summary.trim().isNotEmpty) {
        buffer
          ..writeln(document.summary.trim())
          ..writeln();
      }

      for (final section in document.sections) {
        buffer
          ..writeln('## ${_safeText(section.title)}')
          ..writeln();

        if (section.subtitle.trim().isNotEmpty) {
          buffer
            ..writeln(section.subtitle.trim())
            ..writeln();
        }

        final blocks = List<ResponseBlock>.from(section.blocks)
          ..sort((left, right) => left.priority.compareTo(right.priority));

        for (final block in blocks) {
          if (block.title.trim().isNotEmpty) {
            buffer.writeln('### ${block.title.trim()}');
          }
          buffer
            ..writeln(_safeText(block.content))
            ..writeln();
        }
      }

      if (document.footer.trim().isNotEmpty) {
        buffer
          ..writeln('---')
          ..writeln(document.footer.trim());
      }

      return buffer.toString().trim();
    } catch (_) {
      return '# JourneyMATE AI Brain\n\nUnable to export markdown response.';
    }
  }

  String exportPlainText(ResponseDocument document) {
    try {
      final buffer = StringBuffer()
        ..writeln(_safeText(document.title))
        ..writeln();

      if (document.summary.trim().isNotEmpty) {
        buffer
          ..writeln(document.summary.trim())
          ..writeln();
      }

      for (final section in document.sections) {
        buffer
          ..writeln(_safeText(section.title))
          ..writeln();

        for (final block in section.blocks) {
          if (block.title.trim().isNotEmpty) {
            buffer.writeln('${block.title.trim()}:');
          }
          buffer
            ..writeln(_safeText(block.content))
            ..writeln();
        }
      }

      if (document.footer.trim().isNotEmpty) {
        buffer.writeln(document.footer.trim());
      }

      return buffer.toString().trim();
    } catch (_) {
      return 'JourneyMATE AI Brain\n\nUnable to export plain text response.';
    }
  }

  ResponseSection _buildSingleBlockSection({
    required String title,
    required String subtitle,
    required String blockId,
    required String blockType,
    required String blockTitle,
    required String content,
    required String icon,
    required int priority,
  }) {
    try {
      return ResponseSection(
        title: title,
        subtitle: subtitle,
        blocks: <ResponseBlock>[
          ResponseBlock(
            id: blockId,
            type: blockType,
            title: blockTitle,
            content: _safeText(content),
            icon: icon,
            priority: priority,
          ),
        ],
        metadata: <String, dynamic>{'priority': priority},
      );
    } catch (_) {
      return ResponseSection(
        title: title,
        subtitle: subtitle,
        blocks: <ResponseBlock>[
          ResponseBlock(
            id: blockId,
            type: blockType,
            title: blockTitle,
            content: 'No response content is available.',
            icon: icon,
            priority: priority,
          ),
        ],
      );
    }
  }

  ResponseDocument _fallbackDocument(Object error) {
    return ResponseDocument(
      title: 'JourneyMATE AI Brain',
      summary: 'JourneyMATE generated a safe fallback response.',
      sections: <ResponseSection>[
        generateExplanationSection(
          'The response generator could not format the supplied payload.',
        ),
      ],
      footer: 'Generated by JourneyMATE Intelligent Response Generator.',
      metadata: <String, dynamic>{
        'error': error.toString(),
        'safeFallback': true,
      },
    );
  }

  String _safeText(String value, {String fallback = 'No insight available.'}) {
    final trimmedValue = value.trim();
    return trimmedValue.isEmpty ? fallback : trimmedValue;
  }

  double _safeConfidence(double value) {
    return value.clamp(0.0, 1.0).toDouble();
  }

  Map<String, dynamic> _normalizeMap(dynamic value) {
    if (value is Map) {
      return value.map<String, dynamic>(
        (dynamic key, dynamic entry) =>
            MapEntry<String, dynamic>(key.toString(), entry),
      );
    }
    return <String, dynamic>{};
  }
}
