import 'package:flutter/material.dart';

/// ===============================================================
/// JourneyMATE Enterprise
/// AI Activity Model
/// ---------------------------------------------------------------
/// Represents an activity generated by the AI engine.
/// Used by:
/// • AI Recent Activity
/// • AI Timeline
/// • AI Dashboard
/// • AI Notification (future)
/// ===============================================================

enum AIActivityType { info, success, warning, error }

@immutable
class AIActivity {
  const AIActivity({
    required this.id,
    required this.title,
    required this.description,
    required this.icon,
    required this.type,
    required this.createdAt,
  });

  /// Unique Activity ID
  final String id;

  /// Activity Title
  final String title;

  /// Activity Description
  final String description;

  /// Leading Icon
  final IconData icon;

  /// Activity Type
  final AIActivityType type;

  /// Timestamp
  final DateTime createdAt;

  AIActivity copyWith({
    String? id,
    String? title,
    String? description,
    IconData? icon,
    AIActivityType? type,
    DateTime? createdAt,
  }) {
    return AIActivity(
      id: id ?? this.id,
      title: title ?? this.title,
      description: description ?? this.description,
      icon: icon ?? this.icon,
      type: type ?? this.type,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'description': description,
      'type': type.name,
      'createdAt': createdAt.toIso8601String(),
    };
  }

  factory AIActivity.fromJson(Map<String, dynamic> json) {
    return AIActivity(
      id: json['id'] as String,
      title: json['title'] as String,
      description: json['description'] as String,
      icon: Icons.auto_awesome_rounded,
      type: AIActivityType.values.firstWhere(
        (e) => e.name == json['type'],
        orElse: () => AIActivityType.info,
      ),
      createdAt: DateTime.parse(json['createdAt'] as String),
    );
  }

  @override
  String toString() {
    return 'AIActivity(title: $title, type: ${type.name})';
  }
}
